"""added indices

Revision ID: 1bd6a4a21c9f
Revises: b2ea5250ebed
Create Date: 2018-12-10 16:04:40.880530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd6a4a21c9f'
down_revision = 'b2ea5250ebed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_brand_name'), 'brand', ['name'], unique=False)
    op.create_index(op.f('ix_synonym_synonym'), 'synonym', ['synonym'], unique=True)
    op.drop_constraint('synonym_synonym_key', 'synonym', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('synonym_synonym_key', 'synonym', ['synonym'])
    op.drop_index(op.f('ix_synonym_synonym'), table_name='synonym')
    op.drop_index(op.f('ix_brand_name'), table_name='brand')
    # ### end Alembic commands ###
