"""added sentiment stuff to brand

Revision ID: 1dc6121fa692
Revises: 1bd6a4a21c9f
Create Date: 2018-12-11 11:11:46.821666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc6121fa692'
down_revision = '1bd6a4a21c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('sentiment_average', sa.Float(), nullable=True))
    op.add_column('brand', sa.Column('sentiment_trend', sa.Float(), nullable=True))
    op.add_column('brand', sa.Column('sentiment_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand', 'sentiment_updated_at')
    op.drop_column('brand', 'sentiment_trend')
    op.drop_column('brand', 'sentiment_average')
    # ### end Alembic commands ###
