"""renamed date column

Revision ID: bb76eccd3519
Revises: bb89c6ef11c0
Create Date: 2018-12-11 16:23:03.171699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb76eccd3519'
down_revision = 'bb89c6ef11c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('next_update_at', sa.DateTime(), nullable=True))
    op.drop_column('brand', 'statistics_updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('statistics_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('brand', 'next_update_at')
    # ### end Alembic commands ###
